[project]
name = "00-ai-engineering-bootcamp-cohort-2"
version = "0.1.0"
description = "And your description"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "google-genai>=1.41.0",
    "groq>=0.32.0",
    "ipykernel>=6.30.1",
    "openai>=2.1.0",
]
